Feature/cumulus 16
podaac/tig pull request #32
Opened 2023-11-20 22:39 UTC by sliu008

- Upgrade tig to support cumulus 16
- update cli generate configuration function to be able to use function from python

2023-11-21 17:54 UTC, skorper requested changes
Please upgrade to `cumulus-process` 1.3.0

2023-11-21 18:34 UTC, sliu008 commented
> Please upgrade to `cumulus-process` 1.3.0
> 
> Example: https://github.com/podaac/cumulus-granule-to-cnm/pull/11/files

@skorper it was already update in the lock files ... i updated the pytoml to explicitly make it greater than 1.3.0

2023-11-30 22:59 UTC, skorper approved these changes

2023-11-30 23:45 UTC, jamesfwood approved these changes

2023-11-30 23:47 UTC, merged